name: Label and Assign Issues

on:
  issues:
    types:
      - reopened
      - opened

jobs:
  label_and_assign_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add label to issue
        run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: triage
      
      - name: Assign issue to creator
        run: gh issue edit "$NUMBER" --add-assignee "$ASSIGNEE"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          ASSIGNEE: ${{ github.event.issue.user.login }}
